# Generated by Django 3.0.4 on 2020-03-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoModel',
            new_name='Todo',
        ),
    ]
